import = [
    "~/dotfiles/.config/alacritty/themes/gruvbox_dark.toml"
    # "~/dotfiles/.config/alacritty/themes/catppuccin_macchiato.toml"
    # "~/dotfiles/.config/alacritty/themes/catppuccin_mocha.toml"
]

[cursor.style]
shape = "Block"

[cursor.vi_mode_style]
shape = "Block"

[font]
size = 15

[font.normal]
# family = "Noto Sans Mono"
# family = "IosevkaTerm"
family = "Fira Code"
# family = "JetBrains Mono"
# family = "mononoki nerd font"
style = "Regular"


[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Alt"

[[keyboard.bindings]]
action = "None"
key = "N"
mods = "Command"

[window.padding]
x = 15
y = 15
