theme = "catppuccin_macchiato"
# theme = "base16_transparent"

[editor]
lsp.display-inlay-hints = true
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"
select = "underline"
