# theme = "catppuccin_mocha"
theme = "ayu_evolve"
# theme = "gruvbox"

[editor]
lsp.display-inlay-hints = true
bufferline = "multiple"
cursorline = true

[editor.cursor-shape]
insert = "bar"
select = "underline"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]

[keys.normal."space"]
"<" = "file_picker_in_current_buffer_directory"
